//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Telnet_OMC.WS_CSKH {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="cskhSoap", Namespace="http://tempuri.org/")]
    public partial class cskh : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SendSMS1_VNPTOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendSMS2_800126OperationCompleted;
        
        private System.Threading.SendOrPostCallback SendSMS3_VNPTOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendSMS4_800126OperationCompleted;
        
        private System.Threading.SendOrPostCallback SendSMS5_VNPTOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendSMS6_VNPTOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public cskh() {
            this.Url = global::Telnet_OMC.Properties.Settings.Default.Telnet_OMC_v2_WebReference_cskh;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SendSMS1_VNPTCompletedEventHandler SendSMS1_VNPTCompleted;
        
        /// <remarks/>
        public event SendSMS2_800126CompletedEventHandler SendSMS2_800126Completed;
        
        /// <remarks/>
        public event SendSMS3_VNPTCompletedEventHandler SendSMS3_VNPTCompleted;
        
        /// <remarks/>
        public event SendSMS4_800126CompletedEventHandler SendSMS4_800126Completed;
        
        /// <remarks/>
        public event SendSMS5_VNPTCompletedEventHandler SendSMS5_VNPTCompleted;
        
        /// <remarks/>
        public event SendSMS6_VNPTCompletedEventHandler SendSMS6_VNPTCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendSMS1_VNPT", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendSMS1_VNPT(string receive, string content, string key) {
            object[] results = this.Invoke("SendSMS1_VNPT", new object[] {
                        receive,
                        content,
                        key});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendSMS1_VNPTAsync(string receive, string content, string key) {
            this.SendSMS1_VNPTAsync(receive, content, key, null);
        }
        
        /// <remarks/>
        public void SendSMS1_VNPTAsync(string receive, string content, string key, object userState) {
            if ((this.SendSMS1_VNPTOperationCompleted == null)) {
                this.SendSMS1_VNPTOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendSMS1_VNPTOperationCompleted);
            }
            this.InvokeAsync("SendSMS1_VNPT", new object[] {
                        receive,
                        content,
                        key}, this.SendSMS1_VNPTOperationCompleted, userState);
        }
        
        private void OnSendSMS1_VNPTOperationCompleted(object arg) {
            if ((this.SendSMS1_VNPTCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendSMS1_VNPTCompleted(this, new SendSMS1_VNPTCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendSMS2_800126", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendSMS2_800126(string receive, string content, string key) {
            object[] results = this.Invoke("SendSMS2_800126", new object[] {
                        receive,
                        content,
                        key});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendSMS2_800126Async(string receive, string content, string key) {
            this.SendSMS2_800126Async(receive, content, key, null);
        }
        
        /// <remarks/>
        public void SendSMS2_800126Async(string receive, string content, string key, object userState) {
            if ((this.SendSMS2_800126OperationCompleted == null)) {
                this.SendSMS2_800126OperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendSMS2_800126OperationCompleted);
            }
            this.InvokeAsync("SendSMS2_800126", new object[] {
                        receive,
                        content,
                        key}, this.SendSMS2_800126OperationCompleted, userState);
        }
        
        private void OnSendSMS2_800126OperationCompleted(object arg) {
            if ((this.SendSMS2_800126Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendSMS2_800126Completed(this, new SendSMS2_800126CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendSMS3_VNPT", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendSMS3_VNPT(string _input) {
            object[] results = this.Invoke("SendSMS3_VNPT", new object[] {
                        _input});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendSMS3_VNPTAsync(string _input) {
            this.SendSMS3_VNPTAsync(_input, null);
        }
        
        /// <remarks/>
        public void SendSMS3_VNPTAsync(string _input, object userState) {
            if ((this.SendSMS3_VNPTOperationCompleted == null)) {
                this.SendSMS3_VNPTOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendSMS3_VNPTOperationCompleted);
            }
            this.InvokeAsync("SendSMS3_VNPT", new object[] {
                        _input}, this.SendSMS3_VNPTOperationCompleted, userState);
        }
        
        private void OnSendSMS3_VNPTOperationCompleted(object arg) {
            if ((this.SendSMS3_VNPTCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendSMS3_VNPTCompleted(this, new SendSMS3_VNPTCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendSMS4_800126", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendSMS4_800126(string _input) {
            object[] results = this.Invoke("SendSMS4_800126", new object[] {
                        _input});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendSMS4_800126Async(string _input) {
            this.SendSMS4_800126Async(_input, null);
        }
        
        /// <remarks/>
        public void SendSMS4_800126Async(string _input, object userState) {
            if ((this.SendSMS4_800126OperationCompleted == null)) {
                this.SendSMS4_800126OperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendSMS4_800126OperationCompleted);
            }
            this.InvokeAsync("SendSMS4_800126", new object[] {
                        _input}, this.SendSMS4_800126OperationCompleted, userState);
        }
        
        private void OnSendSMS4_800126OperationCompleted(object arg) {
            if ((this.SendSMS4_800126Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendSMS4_800126Completed(this, new SendSMS4_800126CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendSMS5_VNPT", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendSMS5_VNPT(string _input) {
            object[] results = this.Invoke("SendSMS5_VNPT", new object[] {
                        _input});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendSMS5_VNPTAsync(string _input) {
            this.SendSMS5_VNPTAsync(_input, null);
        }
        
        /// <remarks/>
        public void SendSMS5_VNPTAsync(string _input, object userState) {
            if ((this.SendSMS5_VNPTOperationCompleted == null)) {
                this.SendSMS5_VNPTOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendSMS5_VNPTOperationCompleted);
            }
            this.InvokeAsync("SendSMS5_VNPT", new object[] {
                        _input}, this.SendSMS5_VNPTOperationCompleted, userState);
        }
        
        private void OnSendSMS5_VNPTOperationCompleted(object arg) {
            if ((this.SendSMS5_VNPTCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendSMS5_VNPTCompleted(this, new SendSMS5_VNPTCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendSMS6_VNPT", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendSMS6_VNPT(string receive, string content, string key) {
            object[] results = this.Invoke("SendSMS6_VNPT", new object[] {
                        receive,
                        content,
                        key});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendSMS6_VNPTAsync(string receive, string content, string key) {
            this.SendSMS6_VNPTAsync(receive, content, key, null);
        }
        
        /// <remarks/>
        public void SendSMS6_VNPTAsync(string receive, string content, string key, object userState) {
            if ((this.SendSMS6_VNPTOperationCompleted == null)) {
                this.SendSMS6_VNPTOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendSMS6_VNPTOperationCompleted);
            }
            this.InvokeAsync("SendSMS6_VNPT", new object[] {
                        receive,
                        content,
                        key}, this.SendSMS6_VNPTOperationCompleted, userState);
        }
        
        private void OnSendSMS6_VNPTOperationCompleted(object arg) {
            if ((this.SendSMS6_VNPTCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendSMS6_VNPTCompleted(this, new SendSMS6_VNPTCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void SendSMS1_VNPTCompletedEventHandler(object sender, SendSMS1_VNPTCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendSMS1_VNPTCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendSMS1_VNPTCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void SendSMS2_800126CompletedEventHandler(object sender, SendSMS2_800126CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendSMS2_800126CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendSMS2_800126CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void SendSMS3_VNPTCompletedEventHandler(object sender, SendSMS3_VNPTCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendSMS3_VNPTCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendSMS3_VNPTCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void SendSMS4_800126CompletedEventHandler(object sender, SendSMS4_800126CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendSMS4_800126CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendSMS4_800126CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void SendSMS5_VNPTCompletedEventHandler(object sender, SendSMS5_VNPTCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendSMS5_VNPTCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendSMS5_VNPTCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void SendSMS6_VNPTCompletedEventHandler(object sender, SendSMS6_VNPTCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendSMS6_VNPTCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendSMS6_VNPTCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591